'use client'

import { useResolvedColorMode } from '@language-lit/material3-expressive'
import { shapePath, type ShapeName } from '../theme/shapes'
import { useSiteSource } from '../app/providers'

/**
 * The site's imagery.
 *
 * The page's whole argument is that one source color generates everything, so
 * the pictures are generated too: each shape is cut from the Material 3
 * Expressive vocabulary and filled from a tone of the palette the page is
 * currently painted from. Change the source color and the artwork is recut
 * along with the components, because it is drawing from the same numbers they
 * are. A stock illustration could not make that claim, and a static asset would
 * go stale the moment the theme moved.
 */

type Family = 'primary' | 'secondary' | 'tertiary'

/**
 * A tone stop per color mode.
 *
 * Tonal palettes are absolute: `primary-20` is the same near-black purple
 * whichever mode the page is in, so a composition pinned to fixed tones goes
 * half invisible the moment the surface under it inverts. Each shape therefore
 * carries the tone it should take in each mode, which is the same thing the
 * library's own role mappings do one layer up.
 */
interface Tones {
  readonly light: number
  readonly dark: number
}

interface Placement {
  readonly shape: ShapeName
  /** Grid cell, in the composition's own units. */
  readonly x: number
  readonly y: number
  readonly width: number
  readonly height: number
  readonly family: Family
  readonly tones: Tones
  /** Degrees, about the shape's own center. Fixed, never random. */
  readonly rotate?: number
}

const CELL = 100
const GAP = 12
const span = (cells: number) => cells * CELL + (cells - 1) * GAP
const at = (cell: number) => cell * (CELL + GAP)

/**
 * A deliberate bento rather than a scatter.
 *
 * The shapes tile a four-by-three grid completely, so the composition reads as
 * a designed block rather than as objects floating on a field, and the value
 * structure carries it: one dominant mass, one anchor at the opposite end of
 * the ramp, and lighter shapes opening up the corner. Every stop below exists
 * in the generated palette — the standard tone ladder, not arbitrary numbers.
 *
 * Two families, each walking its own tonal run: primary across four stops and
 * tertiary across three. Secondary is deliberately absent — it is generated at
 * a chroma of 18 against tertiary's 30, so at these sizes it reads as grey mud
 * beside them rather than as a third note. The picture is a palette, so it
 * should look like tones of something, not like an assortment.
 */
const composition: readonly Placement[] = [
  {
    shape: 'clover4',
    x: at(0), y: at(0), width: span(2), height: span(2),
    family: 'primary', tones: { light: 40, dark: 70 },
  },
  {
    shape: 'cookie12',
    x: at(2), y: at(0), width: span(1), height: span(1),
    family: 'tertiary', tones: { light: 60, dark: 50 },
  },
  {
    shape: 'arch',
    x: at(3), y: at(0), width: span(1), height: span(2),
    family: 'primary', tones: { light: 90, dark: 30 },
  },
  {
    shape: 'sunny',
    x: at(2), y: at(1), width: span(1), height: span(1),
    family: 'tertiary', tones: { light: 40, dark: 60 }, rotate: 12,
  },
  {
    shape: 'gem',
    x: at(0), y: at(2), width: span(1), height: span(1),
    family: 'tertiary', tones: { light: 80, dark: 40 },
  },
  {
    shape: 'pill',
    x: at(1), y: at(2), width: span(2), height: span(1),
    family: 'primary', tones: { light: 20, dark: 90 },
  },
  {
    shape: 'circle',
    x: at(3), y: at(2), width: span(1), height: span(1),
    family: 'primary', tones: { light: 70, dark: 50 },
  },
]

const WIDTH = span(4)
const HEIGHT = span(3)

export function ShapeField() {
  const { sourceColor, palette } = useSiteSource()
  const mode = useResolvedColorMode()

  return (
    <svg
      className="shape-field"
      viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
      role="img"
      aria-label={`Material 3 Expressive shapes filled from the tonal palettes generated by the source color ${sourceColor}.`}
    >
      {/*
        Placement lives on the group and the entrance animation lives on the
        path. A CSS transform would otherwise replace the `transform` attribute
        outright rather than composing with it, and every shape would animate
        from the origin instead of from its own cell.
      */}
      {composition.map((placement, index) => (
        <g
          key={placement.shape}
          transform={
            `translate(${placement.x} ${placement.y}) ` +
            `scale(${placement.width / 100} ${placement.height / 100})` +
            (placement.rotate ? ` rotate(${placement.rotate} 50 50)` : '')
          }
        >
          <path
            className="shape-field__shape"
            d={shapePath(placement.shape)}
            fill={palette[`${placement.family}-${placement.tones[mode]}`]}
            style={{ ['--shape-index' as string]: index }}
          />
        </g>
      ))}
    </svg>
  )
}

/**
 * One shape at glyph size, used to give a section or a card its own mark.
 *
 * Categories on the components index get a stable shape so the page gains
 * landmarks a reader can navigate by, rather than decoration that changes
 * meaning nothing.
 */
export function ShapeGlyph({
  shape,
  family = 'primary',
  tones = { light: 50, dark: 70 },
}: {
  shape: ShapeName
  family?: Family
  tones?: Tones
}) {
  const { palette } = useSiteSource()
  const mode = useResolvedColorMode()

  return (
    <svg className="shape-glyph" viewBox="0 0 100 100" aria-hidden focusable="false">
      <path d={shapePath(shape)} fill={palette[`${family}-${tones[mode]}`]} />
    </svg>
  )
}
