'use client'

// Generated by `npm run generate:site-demos` from docs/component-inventory.json.
// Do not edit by hand; `npm run check:site` fails when this file is stale.
//
// The examples are imported statically rather than lazily so every demo is
// server-rendered into the exported HTML. That makes the site a real test of
// the package's SSR and client-boundary behavior (ADR 0028) instead of a
// client-only rendering of it.

import type { ComponentType } from 'react'
import { ButtonExample } from '@examples/Button.example'
import { ButtonGroupExample } from '@examples/ButtonGroup.example'
import { CardExample } from '@examples/Card.example'
import { CheckboxExample } from '@examples/Checkbox.example'
import { CircularProgressExample } from '@examples/CircularProgress.example'
import { DialogExample } from '@examples/Dialog.example'
import { FabMenuExample } from '@examples/FabMenu.example'
import { FloatingActionButtonExample } from '@examples/FloatingActionButton.example'
import { FloatingToolbarExample } from '@examples/FloatingToolbar.example'
import { IconExample } from '@examples/Icon.example'
import { IconButtonExample } from '@examples/IconButton.example'
import { LinearProgressExample } from '@examples/LinearProgress.example'
import { LoadingIndicatorExample } from '@examples/LoadingIndicator.example'
import { MenuExample } from '@examples/Menu.example'
import { NavigationBarExample } from '@examples/NavigationBar.example'
import { NavigationDrawerExample } from '@examples/NavigationDrawer.example'
import { NavigationRailExample } from '@examples/NavigationRail.example'
import { NavigationSuiteExample } from '@examples/NavigationSuite.example'
import { RadioExample } from '@examples/Radio.example'
import { SegmentedButtonGroupExample } from '@examples/SegmentedButtonGroup.example'
import { SelectExample } from '@examples/Select.example'
import { SnackbarExample } from '@examples/Snackbar.example'
import { SplitButtonExample } from '@examples/SplitButton.example'
import { SurfaceExample } from '@examples/Surface.example'
import { SwitchExample } from '@examples/Switch.example'
import { TabsExample } from '@examples/Tabs.example'
import { TextExample } from '@examples/Text.example'
import { TextAreaExample } from '@examples/TextArea.example'
import { TextFieldExample } from '@examples/TextField.example'
import { TooltipExample } from '@examples/Tooltip.example'
import { WavyProgressExample } from '@examples/WavyProgress.example'

export const demoRegistry: Record<string, ComponentType> = {
  Button: ButtonExample,
  ButtonGroup: ButtonGroupExample,
  Card: CardExample,
  Checkbox: CheckboxExample,
  CircularProgress: CircularProgressExample,
  Dialog: DialogExample,
  FabMenu: FabMenuExample,
  FloatingActionButton: FloatingActionButtonExample,
  FloatingToolbar: FloatingToolbarExample,
  Icon: IconExample,
  IconButton: IconButtonExample,
  LinearProgress: LinearProgressExample,
  LoadingIndicator: LoadingIndicatorExample,
  Menu: MenuExample,
  NavigationBar: NavigationBarExample,
  NavigationDrawer: NavigationDrawerExample,
  NavigationRail: NavigationRailExample,
  NavigationSuite: NavigationSuiteExample,
  Radio: RadioExample,
  SegmentedButtonGroup: SegmentedButtonGroupExample,
  Select: SelectExample,
  Snackbar: SnackbarExample,
  SplitButton: SplitButtonExample,
  Surface: SurfaceExample,
  Switch: SwitchExample,
  Tabs: TabsExample,
  Text: TextExample,
  TextArea: TextAreaExample,
  TextField: TextFieldExample,
  Tooltip: TooltipExample,
  WavyProgress: WavyProgressExample,
}

export function getDemo(component: string): ComponentType | undefined {
  return demoRegistry[component]
}
