import { readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const docsRoot = path.join(root, 'docs')
const inventoryPath = path.join(docsRoot, 'component-inventory.json')
const matrixPath = path.join(docsRoot, 'SUPPORTED_COMPONENTS.md')
const writeGenerated = process.argv.includes('--write')
const errors = []

async function exists(target) {
  try {
    await stat(target)
    return true
  } catch {
    return false
  }
}

async function read(relativePath) {
  return readFile(path.join(root, relativePath), 'utf8')
}

const inventory = JSON.parse(await readFile(inventoryPath, 'utf8'))
const packageJson = JSON.parse(await read('package.json'))
const conformant = inventory.components.filter((component) => component.status === 'conformant')

function generateMatrix() {
  const lines = [
    '# Supported components',
    '',
    '<!-- Generated by `npm run generate:docs` from component-inventory.json. -->',
    '',
    `This release contains **${conformant.length} conformant components**. Only rows with`,
    '`conformant` status are an advertised support claim.',
    '',
    '| Component | Kind | Status | Task | Dependencies |',
    '| --- | --- | --- | --- | --- |',
  ]

  for (const component of inventory.components) {
    const name = component.status === 'planned'
      ? `\`${component.name}\``
      : `[\`${component.name}\`](components/${component.name}.md)`
    const dependencies = component.dependencies.length > 0
      ? component.dependencies.map((dependency) => `\`${dependency}\``).join(', ')
      : '—'
    lines.push(
      `| ${name} | ${component.kind} | \`${component.status}\` | \`${component.task}\` | ${dependencies} |`,
    )
  }

  lines.push(
    '',
    'The machine-readable source also records ownership paths and public exports:',
    '[`component-inventory.json`](component-inventory.json). Detailed Material sources,',
    'web adaptations, tests, and verification evidence live in each component\'s',
    'conformance record under `tests/components/`.',
    '',
  )
  return lines.join('\n')
}

const expectedMatrix = generateMatrix()
if (writeGenerated) await writeFile(matrixPath, expectedMatrix)

if (!(await exists(matrixPath))) {
  errors.push('Missing generated docs/SUPPORTED_COMPONENTS.md')
} else if (await readFile(matrixPath, 'utf8') !== expectedMatrix) {
  errors.push('SUPPORTED_COMPONENTS.md is stale; run npm run generate:docs')
}

const componentChecks = {
  example: /```tsx/i,
  anatomy: /\b(root|renders?|element|DOM|native|container|track|thumb|indicator|panel|item|input|button|progress)\b/i,
  'variants or states': /\b(state|states|variant|variants|mode|selected|checked|disabled|open|determinate|indeterminate|orientation|size)\b/i,
  accessibility: /\b(accessib|aria-|keyboard|focus|screen reader|semantic|label)\b/i,
  tokens: /\b(tokens?|--m3e-)\b/i,
}

for (const component of conformant) {
  const relativePath = `docs/components/${component.name}.md`
  const absolutePath = path.join(root, relativePath)
  if (!(await exists(absolutePath))) {
    errors.push(`${component.name} is conformant but has no public component page`)
    continue
  }

  const source = await readFile(absolutePath, 'utf8')
  if (!source.startsWith(`# ${component.name}\n`)) {
    errors.push(`${relativePath} must start with # ${component.name}`)
  }
  for (const [label, pattern] of Object.entries(componentChecks)) {
    if (!pattern.test(source)) errors.push(`${relativePath} does not cover ${label}`)
  }
}

const requiredGuides = [
  'README.md',
  'docs/README.md',
  'docs/GETTING_STARTED.md',
  'docs/THEMING.md',
  'docs/SSR.md',
  'docs/MIGRATION.md',
  'docs/WEB_DEVIATIONS.md',
  'docs/RELEASE_NOTES.md',
  'docs/RELEASE_READINESS.md',
]

for (const guide of requiredGuides) {
  if (!(await exists(path.join(root, guide)))) errors.push(`Missing required public guide: ${guide}`)
}

const rootReadme = await read('README.md')
if (!rootReadme.includes('@language-lit/material3-expressive')) {
  errors.push('README.md does not document the package entry')
}
if (!rootReadme.includes('@language-lit/material3-expressive/styles.css')) {
  errors.push('README.md does not document the complete stylesheet')
}
if (!/does not require Tailwind/i.test(rootReadme)) {
  errors.push('README.md does not state the no-Tailwind setup')
}

const theming = await read('docs/THEMING.md')
for (const requirement of ['createTheme', 'Nested scopes', 'SSR and resolved mode']) {
  if (!theming.includes(requirement)) errors.push(`THEMING.md is missing ${requirement}`)
}

const migration = await read('docs/MIGRATION.md')
for (const requirement of [
  '@language-lit/material3-expressive/styles.css',
  'tailwind-preset',
  'Breaking changes',
]) {
  if (!migration.includes(requirement)) errors.push(`MIGRATION.md is missing ${requirement}`)
}

const releaseNotes = await read('docs/RELEASE_NOTES.md')
if (!releaseNotes.includes(`## ${packageJson.version}`)) {
  errors.push(`RELEASE_NOTES.md has no section for package version ${packageJson.version}`)
}
if (/-/.test(packageJson.version)) {
  errors.push(`the released package version must be stable, received ${packageJson.version}`)
}

if (packageJson.peerDependencies?.tailwindcss || packageJson.peerDependenciesMeta?.tailwindcss) {
  errors.push('Tailwind must not be a peer; the package ships precompiled CSS')
}

const linkedDocs = [...requiredGuides, 'docs/SUPPORTED_COMPONENTS.md']
for (const component of conformant) linkedDocs.push(`docs/components/${component.name}.md`)

for (const relativePath of linkedDocs) {
  const absolutePath = path.join(root, relativePath)
  if (!(await exists(absolutePath))) continue
  const source = await readFile(absolutePath, 'utf8')
  for (const match of source.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)) {
    const target = match[1]
    if (/^(?:https?:|mailto:|#)/.test(target)) continue
    const fileTarget = target.split('#')[0]
    if (!fileTarget) continue
    const resolved = path.resolve(path.dirname(absolutePath), fileTarget)
    if (!(await exists(resolved))) {
      errors.push(`${relativePath} links to missing local file ${target}`)
    }
  }
}

if (errors.length > 0) {
  console.error('documentation check failed:')
  for (const error of errors) console.error(`- ${error}`)
  process.exitCode = 1
} else {
  console.log(
    `documentation check passed (${conformant.length} conformant component pages; package ${packageJson.version})`,
  )
}
